version: "3.8"

services:
  crawler-app:
    image: crawler-app:${TAG:-v0.1}
    depends_on:
      - db
    build:
      context: .
    networks:
      - mynet
    ports:
      - 80:8080
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD:?database password not set}
      - POSTGRES_HOST=${PGHOST}
      - POSTGRES_PORT=${PGPORT}
      - POSTGRES_DB=${PGDATABASE}
    deploy:
      restart_policy:
        condition: on-failure
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    networks:
      - mynet
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD:?database password not set}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - 5432:5432
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

#volumes:
#  pgdata:

networks:
  mynet:
    driver: bridge
